[tool.poetry]
name = "hackaton2023"
version = "0.1.0"
description = ""
authors = ["igor-ht <i_ht93@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
python-telegram-bot = "^13.15"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
